services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    container_name: es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"

volumes:
  es_data: